language: java
sudo: true
dist: precise
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
notifications:
  email:
    recipients:
      - roberto.fitec@gmail.com
    on_success: never # default: change
    on_failure: always # default: always